version: 2.1

jobs:
 test_number_17:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/djibrilfelix52_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e djibrilfelix52@outlook.com
 test_number_18:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/happy.nast_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e happy.nast@outlook.com
 test_number_19:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/alliot.andre_outlook-com.zip -o lunarCrushData.zip
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 57 -r 3 -e alliot.andre@outlook.com
 test_number_20:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/aminatazabuga_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e aminatazabuga@outlook.com
 test_number_21:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/barrfrankmoses1999_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 57 -r 3 -e barrfrankmoses1999@outlook.com
 test_number_22:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/dinhtienhiangfheu_vip-stu-office-gy.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e dinhtienhiangfheu@vip.stu.office.gy
 test_number_23:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/ghinhghidangtuan_vip-stu-office-gy.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e ghinhghidangtuan@vip.stu.office.gy
 test_number_24:
   machine:
      image: ubuntu-2004:202101-01
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/sieunhanasyk_vip-stu-office-gy.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e sieunhanasyk@vip.stu.office.gy
      
      
workflows:
  version: 2

  security_test:
    triggers:
      - schedule:
          cron: "8 0 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "12 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - security_test_17
      - security_test_18
      - security_test_19
      - security_test_20
      - security_test_21
      - security_test_22
      - security_test_23
      - security_test_24
